version: "3"
services:

  mongod11:
    container_name: mongod11
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --replSet mongors1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    expose:
     - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongod11:/data/db

  mongod12:
    container_name: mongod12
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --replSet mongors1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongod12:/data/db

  mongod13:
    container_name: mongod13
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --replSet mongors1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongod13:/data/db

  mongod21:
    container_name: mongod21
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --replSet mongors2 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongod21:/data/db

  mongod22:
    container_name: mongod22
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --replSet mongors2 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongod22:/data/db

  mongod23:
    container_name: mongod23
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --replSet mongors2 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongod23:/data/db

  mongoc1:
    container_name: mongoc1
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --noauth --port 27017
    expose:
         - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongoc1:/data/db

  mongoc2:
    container_name: mongoc2
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --noauth --port 27017
    expose:
         - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongoc2:/data/db

  mongoc3:
    container_name: mongoc3
    image: mongo:3.0.14
    command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr --noauth --port 27017
    expose:
         - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongoc3:/data/db

  mongos1:
    container_name: mongos1
    image: mongo:3.0.14
    depends_on:
      - mongoc1
      - mongoc2
      - mongoc3
    links:
      - mongoc1
      - mongoc2
      - mongoc3
    command: mongos --configdb mongoc1:27017,mongoc2:27017,mongoc3:27017 --port 27017
    ports:
      - 27017:27017
    volumes:
      - /etc/localtime:/etc/localtime:ro

  mongos2:
    container_name: mongos2
    image: mongo:3.0.14
    depends_on:
      - mongoc1
      - mongoc2
      - mongoc3
    links:
      - mongoc1
      - mongoc2
      - mongoc3
    command: mongos --configdb mongoc1:27017,mongoc2:27017,mongoc3:27017 --port 27017
    ports:
      - 27018:27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
